#!/usr/bin/env ruby
Dir.chdir(File.dirname(__FILE__))
`./cleanup`
puts `rsync -av --exclude-from .rsyncexclude . lilydocs.com:ror/lilydocs`
puts `rsync -av --delete  ./app lilydocs.com:ror/lilydocs/app`
